version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/song-microservice

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user

permissions:
  - object: /home/ec2-user/song-microservice
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file

  - object: /home/ec2-user/song-microservice
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory