spring.application.name=songMicroservice
logging.level.root=INFO
logging.level.com.hamza.songmicroservice=DEBUG
stage=${STAGE:dev}
region=${REGION:us-east-1}
grpc.port=${GRPC_PORT:9090}
sqs.published-songs-queue-url=${PUBLISHED_SONGS_QUEUE_URL:}